### ISSUE TITLE
stuck on starting index.js

### ISSUE THREAD

**Issue by sema0205** [Al-Kohollik/discord-simpleRPC#3]
[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,json,ini
[nodemon] starting `node index.js`
and nothing happen
stuck on starting index.js

**Comment by Al-Kohollik** [comment]
That's just where the text ends (for now, I'm planning on adding some stuff to confirm and make everything more clear). If you check your Discord status after it says "starting `node index.js`" it should have already worked and given you your rich presence though.
